package com.github.lppedd.cc.psiElement

import com.github.lppedd.cc.api.CommitToken
import com.intellij.lang.ASTNode
import com.intellij.lang.Language
import com.intellij.lang.documentation.DocumentationProvider
import com.intellij.navigation.ItemPresentation
import com.intellij.openapi.components.service
import com.intellij.openapi.project.Project
import com.intellij.openapi.util.TextRange
import com.intellij.psi.PsiElement
import com.intellij.psi.PsiFile
import com.intellij.psi.PsiManager
import com.intellij.psi.impl.PsiElementBase

/**
 * A fake PSI element generated at completion invocation.
 *
 * The only purposes are to carry the [CommitToken] generated by a Provider
 * and to be passed in to the [DocumentationProvider].
 *
 * @author Edoardo Luppi
 */
internal sealed class CommitTokenPsiElement : PsiElementBase(), ItemPresentation {
  abstract override fun getProject(): Project

  override fun getLanguage(): Language =
    Language.ANY

  override fun getManager(): PsiManager =
    project.service()

  override fun getChildren(): Array<PsiElement> =
    EMPTY_ARRAY

  override fun getParent(): PsiElement? =
    null

  override fun getFirstChild(): PsiElement? =
    null

  override fun getLastChild(): PsiElement? =
    null

  override fun getNextSibling(): PsiElement? =
    null

  override fun getPrevSibling(): PsiElement? =
    null

  override fun getContainingFile(): PsiFile? =
    null

  override fun getTextRange(): TextRange? =
    null

  override fun getStartOffsetInParent(): Int =
    0

  override fun getTextLength(): Int =
    0

  override fun findElementAt(offset: Int): PsiElement? =
    null

  override fun getTextOffset(): Int =
    0

  override fun getText(): String? =
    null

  override fun textToCharArray(): CharArray =
    CharArray(0)

  override fun textContains(char: Char): Boolean =
    false

  override fun isValid(): Boolean =
    true

  override fun isWritable(): Boolean =
    false

  override fun isPhysical(): Boolean =
    false

  override fun getNode(): ASTNode? =
    null

  override fun getLocationString(): String? =
    null

  override fun getPresentation(): ItemPresentation =
    this
}
